benchmarks:
- nghttp2_nghttp2_fuzzer
description: null
docker_registry: gcr.io/fuzzbench
experiment: nghttp201
experiment_filestore: /tmp/experiment-data
fuzzers:
- libfuzzer_ocg
- libfuzzer
git_hash: 6e7b607b1755d42f89987da43a6e27c5d3d30123
local_experiment: true
max_total_time: 43200
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /tmp/report-data
trials: 3
